version: '3'
services:
  app:
    image: golang:1.19-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: go run .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: gouser
      MYSQL_PASSWORD: gouser
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goDB
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    tty: true
    environment:
    - PMA_ARBITRARY=1
    - PMA_USER=root
    - PMA_PASSWORD=root
    ports:
    - 8081:80